/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as BuildRouteImport } from './routes/build'
import { Route as CareerRouteImport } from './routes/career'
import { Route as CareerRoadmapRouteImport } from './routes/career-roadmap'
import { Route as ChallengeRouteImport } from './routes/challenge'
import { Route as ChallengesRouteImport } from './routes/challenges'
import { Route as CodingLabRouteImport } from './routes/coding-lab'
import { Route as CurriculumRouteImport } from './routes/curriculum'
import { Route as CurriculumMapRouteImport } from './routes/curriculum-map'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as LearningModeRouteImport } from './routes/learning-mode'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as RecoveryRouteImport } from './routes/recovery'
import { Route as SkillsRouteImport } from './routes/skills'
import { Route as TutorRouteImport } from './routes/tutor'
import { Route as VerifyCertificateIdRouteImport } from './routes/verify.$certificateId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const BuildRoute = BuildRouteImport.update({
  id: '/build',
  path: '/build',
  getParentRoute: () => rootRouteImport,
} as any)
const CareerRoute = CareerRouteImport.update({
  id: '/career',
  path: '/career',
  getParentRoute: () => rootRouteImport,
} as any)
const CareerRoadmapRoute = CareerRoadmapRouteImport.update({
  id: '/career-roadmap',
  path: '/career-roadmap',
  getParentRoute: () => rootRouteImport,
} as any)
const ChallengeRoute = ChallengeRouteImport.update({
  id: '/challenge',
  path: '/challenge',
  getParentRoute: () => rootRouteImport,
} as any)
const ChallengesRoute = ChallengesRouteImport.update({
  id: '/challenges',
  path: '/challenges',
  getParentRoute: () => rootRouteImport,
} as any)
const CodingLabRoute = CodingLabRouteImport.update({
  id: '/coding-lab',
  path: '/coding-lab',
  getParentRoute: () => rootRouteImport,
} as any)
const CurriculumRoute = CurriculumRouteImport.update({
  id: '/curriculum',
  path: '/curriculum',
  getParentRoute: () => rootRouteImport,
} as any)
const CurriculumMapRoute = CurriculumMapRouteImport.update({
  id: '/curriculum-map',
  path: '/curriculum-map',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const LearningModeRoute = LearningModeRouteImport.update({
  id: '/learning-mode',
  path: '/learning-mode',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const RecoveryRoute = RecoveryRouteImport.update({
  id: '/recovery',
  path: '/recovery',
  getParentRoute: () => rootRouteImport,
} as any)
const SkillsRoute = SkillsRouteImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => rootRouteImport,
} as any)
const TutorRoute = TutorRouteImport.update({
  id: '/tutor',
  path: '/tutor',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyCertificateIdRoute = VerifyCertificateIdRouteImport.update({
  id: '/verify/$certificateId',
  path: '/verify/$certificateId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/analytics': typeof AnalyticsRoute
  '/auth': typeof AuthRoute
  '/build': typeof BuildRoute
  '/career': typeof CareerRoute
  '/career-roadmap': typeof CareerRoadmapRoute
  '/challenge': typeof ChallengeRoute
  '/challenges': typeof ChallengesRoute
  '/coding-lab': typeof CodingLabRoute
  '/curriculum': typeof CurriculumRoute
  '/curriculum-map': typeof CurriculumMapRoute
  '/dashboard': typeof DashboardRoute
  '/learning-mode': typeof LearningModeRoute
  '/onboarding': typeof OnboardingRoute
  '/portfolio': typeof PortfolioRoute
  '/profile': typeof ProfileRoute
  '/projects': typeof ProjectsRoute
  '/recovery': typeof RecoveryRoute
  '/skills': typeof SkillsRoute
  '/tutor': typeof TutorRoute
  '/verify/$certificateId': typeof VerifyCertificateIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/analytics': typeof AnalyticsRoute
  '/auth': typeof AuthRoute
  '/build': typeof BuildRoute
  '/career': typeof CareerRoute
  '/career-roadmap': typeof CareerRoadmapRoute
  '/challenge': typeof ChallengeRoute
  '/challenges': typeof ChallengesRoute
  '/coding-lab': typeof CodingLabRoute
  '/curriculum': typeof CurriculumRoute
  '/curriculum-map': typeof CurriculumMapRoute
  '/dashboard': typeof DashboardRoute
  '/learning-mode': typeof LearningModeRoute
  '/onboarding': typeof OnboardingRoute
  '/portfolio': typeof PortfolioRoute
  '/profile': typeof ProfileRoute
  '/projects': typeof ProjectsRoute
  '/recovery': typeof RecoveryRoute
  '/skills': typeof SkillsRoute
  '/tutor': typeof TutorRoute
  '/verify/$certificateId': typeof VerifyCertificateIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/analytics': typeof AnalyticsRoute
  '/auth': typeof AuthRoute
  '/build': typeof BuildRoute
  '/career': typeof CareerRoute
  '/career-roadmap': typeof CareerRoadmapRoute
  '/challenge': typeof ChallengeRoute
  '/challenges': typeof ChallengesRoute
  '/coding-lab': typeof CodingLabRoute
  '/curriculum': typeof CurriculumRoute
  '/curriculum-map': typeof CurriculumMapRoute
  '/dashboard': typeof DashboardRoute
  '/learning-mode': typeof LearningModeRoute
  '/onboarding': typeof OnboardingRoute
  '/portfolio': typeof PortfolioRoute
  '/profile': typeof ProfileRoute
  '/projects': typeof ProjectsRoute
  '/recovery': typeof RecoveryRoute
  '/skills': typeof SkillsRoute
  '/tutor': typeof TutorRoute
  '/verify/$certificateId': typeof VerifyCertificateIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/analytics'
    | '/auth'
    | '/build'
    | '/career'
    | '/career-roadmap'
    | '/challenge'
    | '/challenges'
    | '/coding-lab'
    | '/curriculum'
    | '/curriculum-map'
    | '/dashboard'
    | '/learning-mode'
    | '/onboarding'
    | '/portfolio'
    | '/profile'
    | '/projects'
    | '/recovery'
    | '/skills'
    | '/tutor'
    | '/verify/$certificateId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/analytics'
    | '/auth'
    | '/build'
    | '/career'
    | '/career-roadmap'
    | '/challenge'
    | '/challenges'
    | '/coding-lab'
    | '/curriculum'
    | '/curriculum-map'
    | '/dashboard'
    | '/learning-mode'
    | '/onboarding'
    | '/portfolio'
    | '/profile'
    | '/projects'
    | '/recovery'
    | '/skills'
    | '/tutor'
    | '/verify/$certificateId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/analytics'
    | '/auth'
    | '/build'
    | '/career'
    | '/career-roadmap'
    | '/challenge'
    | '/challenges'
    | '/coding-lab'
    | '/curriculum'
    | '/curriculum-map'
    | '/dashboard'
    | '/learning-mode'
    | '/onboarding'
    | '/portfolio'
    | '/profile'
    | '/projects'
    | '/recovery'
    | '/skills'
    | '/tutor'
    | '/verify/$certificateId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AnalyticsRoute: typeof AnalyticsRoute
  AuthRoute: typeof AuthRoute
  BuildRoute: typeof BuildRoute
  CareerRoute: typeof CareerRoute
  CareerRoadmapRoute: typeof CareerRoadmapRoute
  ChallengeRoute: typeof ChallengeRoute
  ChallengesRoute: typeof ChallengesRoute
  CodingLabRoute: typeof CodingLabRoute
  CurriculumRoute: typeof CurriculumRoute
  CurriculumMapRoute: typeof CurriculumMapRoute
  DashboardRoute: typeof DashboardRoute
  LearningModeRoute: typeof LearningModeRoute
  OnboardingRoute: typeof OnboardingRoute
  PortfolioRoute: typeof PortfolioRoute
  ProfileRoute: typeof ProfileRoute
  ProjectsRoute: typeof ProjectsRoute
  RecoveryRoute: typeof RecoveryRoute
  SkillsRoute: typeof SkillsRoute
  TutorRoute: typeof TutorRoute
  VerifyCertificateIdRoute: typeof VerifyCertificateIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/build': {
      id: '/build'
      path: '/build'
      fullPath: '/build'
      preLoaderRoute: typeof BuildRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/career': {
      id: '/career'
      path: '/career'
      fullPath: '/career'
      preLoaderRoute: typeof CareerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/career-roadmap': {
      id: '/career-roadmap'
      path: '/career-roadmap'
      fullPath: '/career-roadmap'
      preLoaderRoute: typeof CareerRoadmapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/challenge': {
      id: '/challenge'
      path: '/challenge'
      fullPath: '/challenge'
      preLoaderRoute: typeof ChallengeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/challenges': {
      id: '/challenges'
      path: '/challenges'
      fullPath: '/challenges'
      preLoaderRoute: typeof ChallengesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coding-lab': {
      id: '/coding-lab'
      path: '/coding-lab'
      fullPath: '/coding-lab'
      preLoaderRoute: typeof CodingLabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/curriculum': {
      id: '/curriculum'
      path: '/curriculum'
      fullPath: '/curriculum'
      preLoaderRoute: typeof CurriculumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/curriculum-map': {
      id: '/curriculum-map'
      path: '/curriculum-map'
      fullPath: '/curriculum-map'
      preLoaderRoute: typeof CurriculumMapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learning-mode': {
      id: '/learning-mode'
      path: '/learning-mode'
      fullPath: '/learning-mode'
      preLoaderRoute: typeof LearningModeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recovery': {
      id: '/recovery'
      path: '/recovery'
      fullPath: '/recovery'
      preLoaderRoute: typeof RecoveryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skills': {
      id: '/skills'
      path: '/skills'
      fullPath: '/skills'
      preLoaderRoute: typeof SkillsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tutor': {
      id: '/tutor'
      path: '/tutor'
      fullPath: '/tutor'
      preLoaderRoute: typeof TutorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify/$certificateId': {
      id: '/verify/$certificateId'
      path: '/verify/$certificateId'
      fullPath: '/verify/$certificateId'
      preLoaderRoute: typeof VerifyCertificateIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AnalyticsRoute: AnalyticsRoute,
  AuthRoute: AuthRoute,
  BuildRoute: BuildRoute,
  CareerRoute: CareerRoute,
  CareerRoadmapRoute: CareerRoadmapRoute,
  ChallengeRoute: ChallengeRoute,
  ChallengesRoute: ChallengesRoute,
  CodingLabRoute: CodingLabRoute,
  CurriculumRoute: CurriculumRoute,
  CurriculumMapRoute: CurriculumMapRoute,
  DashboardRoute: DashboardRoute,
  LearningModeRoute: LearningModeRoute,
  OnboardingRoute: OnboardingRoute,
  PortfolioRoute: PortfolioRoute,
  ProfileRoute: ProfileRoute,
  ProjectsRoute: ProjectsRoute,
  RecoveryRoute: RecoveryRoute,
  SkillsRoute: SkillsRoute,
  TutorRoute: TutorRoute,
  VerifyCertificateIdRoute: VerifyCertificateIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
